### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by twongjirad** [NevisUB/LArOpenCV#1]
Is a header missing?

on fmwk_update:

make[3]: Entering directory '/home/twongjirad/working/larbys/dllee_unified/LArOpenCV/LArOpenCV/ImageCluster/AlgoModule'
<< checking dependencies >>
In file included from MatchAnalysis.cxx:4:0:
MatchAnalysis.h:7:61: fatal error: LArOpenCV/ImageCLuster/AlgoClass/AtomicAnalysis.h: No such file or directory
 #include "LArOpenCV/ImageCLuster/AlgoClass/AtomicAnalysis.h"

**Comment by twongjirad** [comment]
oops its there. I think there is a typo in the include statement.

**Comment by vgenty** [comment]
yeah my bad... if you wouldn't mind correcting

**Comment by twongjirad** [comment]
done.
